Exam
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #15
Opened 2024-12-23 18:27 UTC by gudzan

# Экзамен

Прошу @martinkomitsky, @haseprogram проверить.

- [x] В корневой папке репозитория создать базовое приложение exam с помощью vite по инструкции
- [x] Сверстать 2 страницы и необходимые компоненты
- [x] Использовать стили. Дизайн должен быть похожим на макет
- [x] Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- [x] Реализовать перевод с неизвестного языка (автоопределитель из API)
- [x] Сохранять историю переводов в localStorage
- [x] Использовать Redux (редакс добавила, но сами действия добавления и удаления истории еще не успела протестировать)
- [x] Использовать React-router для перехода между страницами
- [x] Задеплоить решение, используя GitHub Actions
 Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-23 18:36 UTC, gudzan commented
Экзамен закончился после моего коммита "exam | fix"  -  d0005e643776d6bbff071ff4184bcc21a62fd0d0

2024-12-23 20:10 UTC, gudzan commented
после экзамена
* потестила редакс, работает!
* добавила новый тип данных languageOption, для удобства
* навесила ссылку в хэдере на "VK Translate", чтобы можно было вернуться на Home страницу
* добавила кнопку очистить историю
* все взаимодействие с localstorage перенесла в redux actions
* добавила совсем немного стилей

Примечание: Отправить текст на перевод можно нажав клавишу Enter

2024-12-28 12:34 UTC, HaseProgram requested changes
Привет, очень хорошая работа, есть всего лишь пара замечаний.
Но пока готов поставить 42 (из 46). Хочется еще чуть-чуть более похожий дизайн (концепт есть, красивостей нет). Если захочешь - можно доделать и дополучить баллы, заодно тогда и key поправить)

2024-12-28 12:34 UTC, HaseProgram commented on exam/src/components/HistoryItems/HistoryItems.tsx
> +        {history.map((item) =>
Не хватает key

2024-12-28 12:34 UTC, HaseProgram commented on exam/src/components/TranslateForm/TranslateForm.tsx
> +      e.preventDefault();
А зачем првентить? Обрезаем себе возможность переводить многострочный текст. Плюс нембольшой баг - первый enter сработает и переведет каретку, второй уже нет и отправит пустой запрос

2024-12-28 12:34 UTC, HaseProgram commented on exam/src/components/TranslateForm/TranslateForm.tsx
> +    const selectedValue = languages[selectedKey as keyof typeof languages];
А автодетект нельзя выбрать, если уже был выбран какой-то другой язык :)

2024-12-28 12:34 UTC, HaseProgram commented on exam/src/components/TranslateForm/TranslateForm.tsx
> +    }
Копипаста, кажется, можно было бы как-то объединить с другим обработчиком

2024-12-28 13:55 UTC, gudzan commented
Исправила несколько замечаний. Дизайн еще не поправила. Дизайн поправлю чуть позже обязательно!
Изменения:
* Добавила key и генерацию случайного id. Если в localStorage есть данные без id, то для отображения будет подставляться случайный id
* Убрала preventDefault
* Объединила обработчики выпадающих списков в один handleChangeLanguage
* Теперь можно выбирать автодетект, если уже был выбран какой-то другой язык
* Теперь нельзя отправить запрос с пустым текстом для перевода

2025-01-07 13:25 UTC, gudzan commented
https://gudzan.github.io/2024-2-VK-EDU-Frontend-A-Gudz/

Постаралась приблизить дизайн к макету. Но на макете не очень понятно, где располагается кнопка перехода на страницу История, поэтому поставила ее рядом с Text.

![image](https://github.com/user-attachments/assets/48fa589a-5c1e-4f88-939f-cb9300b9fe6c)

2025-01-12 18:43 UTC, HaseProgram approved these changes
Теперь стало совсем классно, до максимума добавил :))

2025-01-12 18:43 UTC, merged