ДЗ 2
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #2
Opened 2024-09-26 13:34 UTC by gudzan

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Изменила алгоритм nonUniqueElements из первого ДЗ. Основная причина: сложность O(n^2). Убрала цикл в цикле. Теперь сложность должна быть О(n) (или O(2n))
* Сверстала чат. Расположение элементов примерно оставила то же, что и на макете. Однако, решила немного изменить стиль. Надеюсь, что так можно.
* Посмотреть готовую работу можно по ссылке: https://gudzan.github.io/2024-2-VK-EDU-Frontend-A-Gudz/

2024-09-26 13:35 UTC, gudzan commented on nonUniqueElements.js
>  }
Вот тут поменяла алгоритм

2024-09-27 17:03 UTC, RomanBarannickov requested changes
1.UI хорош, но решение спорное чтоб всегда отображать почти как мобильную версию
2. при клике мышкой на кнопку отправки, теряется фокус с инпута. Надо чтоб не терялся
3. не хватает адаптивности, даже на мобиле у тебя огромные отступы по бокам и вроде мобильная версия выглядит плохо
![image](https://github.com/user-attachments/assets/6796fae2-57c8-4824-881b-a1ced55a9ed5)

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <div class="message__inner">
для сообщений используй ul и li
для в целом контейнера используй тег main https://doka.guide/html/main/

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <div class="material-icons form__button-send">send</div>
вместо div используй button
у button есть специальный тип для отправки формы submit
https://doka.guide/html/button/

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +  <form class="form" action="/">
оберни тегом footer

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +  <script src="index.js"></script>
скрипты лучше помещать внизу body после всех тегов
это лучше со стороны оптимизации приложения

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +function toggleDropdown() {
преимущественно используются в современной разработке только стрелочные функции
перепиши на них лучше
function вне классов и объектов можно считать устаревшим видом как var из за своей особенности всплытия и усложнения в читабельности кода

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +  if (json !== null) {
лучше делать обратные проверки чтоб уменьшать вложенность
if(!json) {
return 
}
do logic

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +  let json = localStorage.getItem(MESSAGES_LOCALSTORAGE);
если переменная не изменяется, лучше использовать const вместо let

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +}
конечно ок
но твоя функция не соответствует описанию
она и в сторадж сохраняет и массив мутирует ещё, а это сайд эффект, функции с сайд эффектами лучше стараться писать по минимуму
лучше разделить эти логики 

и вообще на 60 строке ты и так добавляешь в массив текст, зачем и тут это ещё делать?

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +  let messageText = document.createElement("div");
тексты лучше класть в более семантичный тег типа span

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +  }
тут так же убери вложенность и сделай более простую проверку
лучше по возможности такие проверки с НЕ, писать по меньше, т.к человеческий мозг их плохо понимает

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +}
если добавишь кнопку в форму и типом верным, то эта функция не понадобиться

2024-09-27 17:03 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    }
Не обязательно к исправление
в целом ок решение и даже быстро работает так как UI довольно простой
но хочу заметить, на каждый addMessageToList происходить repaint и reflow, что в свою очередь может сказать на производительности приложения
как насчет того чтобы собрать все сообщения в одном контейнере и уже непосредственно этот контейнер вставить одним appendChild с единой перерисовкой в UI

статья должна помочь с оптимизацией
https://learn.javascript.ru/modifying-document

2024-09-28 19:13 UTC, gudzan commented
Постаралась все пункты исправить. Только desktop версию пока оставила некрасивой, растягивать на весь экран не хочется. Надеюсь, в следующих домашних заданиях добавим по бокам элементов, и будет по-лучше

2024-09-29 15:43 UTC, RomanBarannickov approved these changes
@gudzan респект, что все поправила, но советую все таки в будущем писать преимущественно на стрелочных функциях, а не на обычных)
 
@martinkomitsky, @HaseProgram, @kgrechin -апрув

2024-10-01 21:38 UTC, HaseProgram approved these changes
Огонь, 12!

2024-10-01 21:39 UTC, merged