Dz3
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #3
Opened 2024-10-07 18:53 UTC by gudzan

# Домашнее задание №3
Прошу @martinkomitsky, @HaseProgram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Удалила первую домашку
* Переехала на vite
* Сделала вторую страницу с чатами

Посмотреть готовую работу можно по ссылке: https://gudzan.github.io/2024-2-VK-EDU-Frontend-A-Gudz/

2024-10-08 11:27 UTC, RomanBarannickov requested changes
по UI
1. прикольная реализация добавления нового чата с бесконечными картинками, лайк
2. в целом дизайн прикольный
3. Желательно, кнопка поиска в фильтрах должна работать и фильтровать
4. Хотелось бы иметь возможность как то самому называть чат
5. чтоб у вновь созданных чатов отображались последние сообщения
6. при заходе в чат, хотелось бы чтоб сразу был фокус на поле ввода, чтоб сразу начать писать сообщения
7. в чате сообщения для десктопа прижать к левому краю, чек как в телеге сделано

По js
1. пересмотри своё отношение к let и const. Если переменная не меняется, не меняется её значение, если это примитив, и не меняется ссылка, если это объект, то предпочтительнее использовать const
2. порядок определения и стрелочные функции. Стрелочные функции можно считать были специально придуманы, потому что эффект всплытия, которым ты пользуешься активно, имеет побочное действие в виде сложно читабельного кода и лапши. Когда пишешь на функциях, которые определенны в переменной, приходится писать последовательный код. А то сейчас выглядит так, как если бы представь, инструкция по сборке стола была с самого конца
сначала в файле идут импорты
потом идут переменные и определение функций
дальше уже их взаимодействие и их отношения между собой
3. Код в целом оставил положительные впечатления. Ничего ужасного нет, в целом больше рекомендации и небольшие правки требуются. Молодец, так держать

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/mockData/userList.json
> +    "id": "0",
id Все таки обычно с 1 начинается

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +  console.log(chats);
дебаг убираем

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +  const chatsFromLocalStorage = JSON.parse(json);
эту логику получения чата из стора, лучше вынести в отдельную функцию

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +function loadChatsFromLocalStorage() {
стрелочные функции предпочтительнее

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +    "id": (chatId++).toString(),
в целом можно просто любой рандомный id задавать
лучше напиши какую та функцию генерации id и используй её, чтоб ручками каждый раз не делать это

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +newChatButton.addEventListener("click", () => {
лучше вынести логику непосредственно из листнера
и отдельно именованную функцию в листнер передавать
так меньше вложенность и выше читабельность

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +  localStorage.setItem(CHATS_LOCALSTORAGE, JSON.stringify(chats));
так же лучше вынести логику записи чатов в стор с преобразованием в отдельную функцию

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +printChatsFromArray(userList)
принято сначала описывать функции с переменными
и только потом их применять

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +let chats = []
1. const предпочтительнее let. let подразумевает, что переменная будет изменяться, в данном контексте, ссылки на объекты остаются прежними

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/index.js
> +const CHATS_LOCALSTORAGE = 'CHATS';
вот тут хорошо вынесла и назвала

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/chat.js
> +let messageId = 0;
id c 1

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/chat.js
> +  const messagesFromLocalStorage = JSON.parse(json);
эту логику в отдельную функцию

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/chat.js
> +  localStorage.setItem(MESSAGES_LOCALSTORAGE, JSON.stringify(messages));
эту логику в отдельную функцию

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/js/chat.js
> +  const usersMessage = messagesJson.find((element) => element.userId === params.toString())
если в твоих params не окажется твоего id который ты запросила выше?
если бы мы писали на TS, он бы сказал, что метод get в таких случаях выдаст string | undefined

2. получения чата по айди тоже лучше вынести в отдельную функцию. Функцию должна принимать айди, а не брать его из общего контекста

2024-10-08 11:27 UTC, RomanBarannickov commented on simple-chat/src/common/printMessage.js
> +  let messageInfoTime = document.createElement("span");
const

2024-10-08 11:27 UTC, RomanBarannickov commented on .gitignore
погугли шаблон gitignore для веб разработки, чтоб не переписывать на каждый чих этот файл

2024-10-10 11:11 UTC, gudzan commented
* сделала поиск по чатам с дебаунсом (закрывается на крестик или esc как в телеге)
* добавила модальное окошко для названия нового чата
* при создании чата создается первое сообщение
* после отправки сообщения оно теперь отображается как последнее сообщение в списке всех чатов
* добавила фокус на поле ввода при входе в чат, при открытии модального окна и строки поиска
* для десктопа прижала все сообщения к левому краю
* переделать структуру js файлов, сделать везде стрелочные функции, поменяла местами описание функций и вызов функций
* сделала функцию для создания рандомных id в виде uuid
* вынесла работу со всеми данными в отдельный js

2024-10-13 18:10 UTC, RomanBarannickov approved these changes
апрув 
@martinkomitsky, @HaseProgram, @kgrechin

2024-10-17 20:44 UTC, martinkomitsky commented
12!

2024-10-17 20:44 UTC, merged