Dz5
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #5
Opened 2024-10-21 18:27 UTC by gudzan

# Домашнее задание №5

Прошу @martinkomitsky, @HaseProgram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Перенесла все на реакт

Посмотреть готовую работу можно по ссылке: https://gudzan.github.io/2024-2-VK-EDU-Frontend-A-Gudz/

2024-10-22 11:05 UTC, RomanBarannickov requested changes
в целом всё круто, так держать
небольшие доработки и всё будет супер

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatRow/ChatRow.jsx
> +      <a className="chat__link" onClick={() => setChatId(chat.id)}>
лучше выносить из jsx по максимальному логику любую, даже самую простую на первый взгляд, потом будет проще поддерживать

то есть вынеси вычисление класса в переменную и клик тоже в переменную и уже их передавай в jsx

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatRow/ChatRow.jsx
> +        <img src={chat.userAvatar} />
у img обязательно надо указывать alt
чтоб если в каких то случаях картинка не загрузилась, показался текст какой то, ну и на доступность это тоже влияет для screenreader
https://doka.guide/a11y/chto-takoe-a11y/

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatsList/ChatList.jsx
> +        )}
такие вещи лучше изображать через if 
1. выносим проверку длинны массива в переменную
2. `if (empty) {
return <span>
}

return <ul>`

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/components/Message/Message.jsx
> +    </li>
выносим всю логику из jsx
меньше логики в jsx 
1. легче читать
2. легче поддерживать

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/components/MessagesList/MessagesList.jsx
> +        <Message key={message.id} message={message} isNew={newMessage !== null && message.id === newMessage.id} />
и тут тоже выносим логику вычисления

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/page/PageChat/PageChat.jsx
> +    messagesRef.current.scrollTop = messagesRef.current.scrollHeight
там должен быть метод просто shttps://doka.guide/js/element-scrollto/

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/page/PageChat/PageChat.jsx
1. выносим все функции и логику вычисления из jsx в переменные перед return
2. следуем компонентному подходу. Header и Footer лучше вынести хотя бы рядышком в отдельные компоненты
3. Возможно стоит рассмотреть вариант создания компонента page, который бы оборачивал все страницы с каком то общей логикой. Типа одна и таже логика css с позиционированием и тп. Обычно это ещё называют layout

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/page/PageChatList/PageChatList.jsx
Все те же комментарии, что и к странице page chat

2024-10-22 11:05 UTC, RomanBarannickov commented on react-chat/src/service/dataService.js
советую разбить этот файл уже на несколько
тип создать папочку api
там создать папки с каждой сущностью chat user messages
и в каждой папке отдельной описать методы взаимодействия с каждой сущностью

2024-10-25 15:31 UTC, gudzan commented
* вынесла логику из разметки, все расположила до return
* добавила alt на картинки
* scrollTop заменила на scrollTo
* добавила Layout и вынесла в него стили header-ов
* вынесла со страниц header-ы и footer
* разбила работу с localStorage на отдельные части
* вроде ничего не сломала :)

2024-10-30 13:52 UTC, RomanBarannickov submitted a review, later dismissed
@martinkomitsky, @HaseProgram, @kgrechin 
апрув 

@gudzan всё круто, молодец! Оставил рекомендации, в остальном всё класс

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/DropdownChatMenu/DropdownChatMenu.scss
> +}
ты можешь так же вкладывать в друг друга классы просто ссылаясь на них через &
https://sass-lang.com/guide/

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/DropdownChatMenu/index.js
> +export default DropdownChatMenu;
так как ты тут сразу делаешь export default 
можно сразу вот так прописать без импорта
export {default} from './component'

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/FooterChat/FooterChat.scss
> +}
можно вроде бы вот так сразу записать внутри класса
&__input[type="submit"]

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/FooterChat/FooterChat.scss
> +.footer-form__input {
Вот тут точно работает схема 
&__input

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/FooterChat/index.js
упоминал что можно без реимпорта и сразу export

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageChat/HeaderPageChat.jsx
> +  const toggleDropdown = () => setOpenDropdown(!openDropdown)
лучше не использовать значение из стейта для переведения в обратное состояние
лучше использовать свойства сеттера стейта, который может принять колбек
setOpenDropdownd((oldState) => !oldState)
это связано с тем, что в момент toggle в теории состояние может быть ещё не измененным на обратное значение и могут происходить всякие коллизии, т.к реакт по факту стейт меняет асинхронно под капотом

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageChat/HeaderPageChat.scss
> +}
уже упоминал про возможности scss для сокращения кода с &__user
можно даже дважды вложить

2024-10-30 13:52 UTC, RomanBarannickov commented on react-chat/src/components/Message/Message.jsx
> +  const infoClassName = `message__info ${message.sender === 1 ? "message__info--my" : "message__info--another"}`
я думаю можно подрубить библиотеку https://www.npmjs.com/package/classnames
чтоб было чуть полегче с выводом классов

2024-10-30 13:52 UTC, RomanBarannickov approved these changes

2024-10-31 06:46 UTC, HaseProgram approved these changes
Отлчино, 12!

2024-10-31 06:46 UTC, merged