Dz6
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #6
Opened 2024-10-31 13:41 UTC by gudzan

# Домашнее задание №6

Прошу @martinkomitsky, @HaseProgram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Подключила react-router
* Сделала страницу профиля

2024-11-01 15:36 UTC, RomanBarannickov requested changes
всё ок, но не выполнено одно условие дз по hash роутеру и сомнение есть в возможности использования lodash - но это мелочи

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/index.scss
> -  justify-content: space-between;
если не надо то удаляем

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +  const baseUrl = '/2024-2-VK-EDU-Frontend-A-Gudz'
воу воу воу
это мы так не используем
baseUrl у тебя указан в vite конфиге
я глянул у тебя не правильно указан base  в vite
укажи его как полный домен https://gudzan.github.io/2024-2-VK-EDU-Frontend-A-Gudz
и тогда все заведется

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +    <BrowserRouter>
используем hash роутер - это условие дз

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +        <Route path={`${baseUrl}/my-profile`} element={<PageMyProfile />} />
все url путей мы выносим в словарик и используем этот словарик. Чтоб была одна точка входа в знания о том как называются пути и их было можно легко поменять в одном месте и сразу во всем проекте
словарь - это просто объект в котором лежит ключ значение  вида
const ROUTES = {root: '/', chats: '/chats'} и тп

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/components/ChatRow/ChatRow.jsx
> +      <Link className="chat__link" to={`chat/${chat.id}`}>
используем словарь

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/components/DropdownChatListMenu/DropdownChatListMenu.jsx
> +  const dropdownClassName = `dropdown profile ${openDropdown ? `open` : `close`}`
советую все же присмотреться к https://www.npmjs.com/package/classnames

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/components/DropdownChatListMenu/DropdownChatListMenu.jsx
> +          <Link to={`my-profile`}>
в словарь

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageChat/HeaderPageChat.jsx
> +        <Link to="/2024-2-VK-EDU-Frontend-A-Gudz">
поправишь base и будет просто /
и плюс так же из словаря достаем пути

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageMyProfile/HeaderPageMyProfile.jsx
> +        <Link to="/2024-2-VK-EDU-Frontend-A-Gudz">
из словаря

2024-11-01 15:36 UTC, RomanBarannickov commented on react-chat/src/page/PageMyProfile/PageMyProfile.jsx
> +import _ from "lodash"
лодаш очень и очень большой. Лучше доставай из него на прямую только те функции, которые действительно нужны, чтоб не разбухал бандл проекта

2024-11-01 15:37 UTC, RomanBarannickov commented
и не уверен, можно ли было удалять папку с simple chat

2024-11-02 15:59 UTC, gudzan commented
* добавила словарь с роутами
* заменила base
* добавила HashRouter
* добавила classnames

2024-11-05 14:19 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-11-06 10:02 UTC, merged

2024-11-06 10:02 UTC, martinkomitsky commented
12!