Dz7
gudzan/2024-2-VK-EDU-Frontend-A-Gudz pull request #7
Opened 2024-11-05 21:19 UTC by gudzan

# Домашнее задание №7

Прошу @martinkomitsky, @HaseProgram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Подключила все экраны, что у меня были к бэку
* Использовала polling для обмена сообщениями
* отзыв приложила к лекции 8 (вроде это был обязательный пункт дз)

Вижу, что в апи больше возможностей, чем у меня экранов. Поэтому пока что сделала несколько заглушек:
* Создание нового чата пока доступно только по id пользователя. Буду делать
* Поиск по чатам реализован на бэке только по группам, а не по личным чатам. У меня сейчас только личные чаты, поэтому поиск старательно ищет, но пока ничего не находит.

2024-11-09 09:44 UTC, RomanBarannickov requested changes
# Страница логина
1. Было бы круто добавить вывод ошибки на запрос /auth

# Страница регистрации
1. поехала немного верстка 
![image](https://github.com/user-attachments/assets/d14208a4-b828-46c2-93b1-ef29a7777d8a)
2. было бы круто добавить подсветку Либо сразу валидацию ошибок либо подсветку ошибок приходящих с бека. Либо и то и другое, если бек отдал не ожиданную ошибку 
![image](https://github.com/user-attachments/assets/8471013b-b68a-48b8-a8a5-b4cfedbdd09e)
3. было бы классно добавить возможность посмотреть введенный пароль
4. возможно стоит добавить поле подтверждения верности пароля

# Страница чатов
1. идет дублирование запроса /chats. 
![image](https://github.com/user-attachments/assets/c8a88f0c-322e-4551-930f-f21146f0dc95)
2. Не хватает основных запросов инициализации приложения как по мне. Надо сразу подтягивать всех пользователей.
3. Надо сделать на странице чатов long pulling. Опрашивать сервер о новых чатах и новых сообщениях в уже созданных чатах. Ну раз там в 20 секунд думаю будет приемлемо. А то сейчас как то Динамики не хватает немного

# Страница сообщений
1. идет дудос сервера 
![image](https://github.com/user-attachments/assets/2dd78719-e009-4996-a782-86af442603c7)
Из за этого лагает UI и вообще так нельзя. Назвать это long pulling тоже нельзя. Это прям дудос) Видимо где то запрос не в useEffect, а просто в компоненте. 


# Страница профиля
1. не много едет верстка когда нет аватарки. 
![image](https://github.com/user-attachments/assets/da0f971f-411f-4706-a3a0-23bcd353e6fb)
Наверное стоит добавить проверку на то, что нет аватарки и ставить какую нибудь дефолтную заглушку фотики


@gudzan 
В общем и целом все круто и сильно. Просто много рекомендаций. Но не ставлю апрув, за очень дудосный long pulling в сообщениях. Поправь его и тогда поставлю апрув

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/PrivateRoute/PrivateRoute.jsx
> +  }
можно без else

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageRegister/PageRegister.scss
удаляем

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/api.config.js
> +    }
1. кажется, что проверка на url в данном случае не особо требуется. Т.к по логике вещей. Когда пользователь регистрируется, никакого аксес токена у него не может быть

2. Лучше добавить проверку на существования аксес токена. А то в целом можно представить ситуацию, что на бек летит запрос с хедером Bearer undefined или null. Такие вещи лучше наверника проверять

3. да и в целом бек мне кажется мимо себя пропустит заголовок авторизации для апи регистрации. Просто потому что сам по себе его там не ожидает увидеть.

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/api.config.js
> +  baseURL: "https://vkedu-fullstack-div2.ru/"
используем env переменные для таких вещей

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/api.config.js
> +};
все круто. Но потом на ts будет тяжело писать. Лучше сразу методы отделять от реализации
тип get: (getParams) => instance.get(getParams) // условный код
а то сейчас по факту вроде абстракция есть, но не совсем. А добавляя непосредственно методы. Мы прям вводим понятие интерфейса и уже без разницы что там внутри get метода будет axios или не axios

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/auth/authService.js
> +export default authService;
не совсем это сервис. Мы же находимся в папе api. Лучше назвать это authApi. И вызывать здесь только апи без всякий сайд эффектов

Потом в отдельной папки services - сделать уже authService и там вызвать authApi и уже обрабатывать результаты вызова апи.

префикс /api Советую вынести сразу в какую та общую глобальную переменную для всех api или даже добавлять её лучше в инстансе axios к baseUrl. Бывает, что бек меняет там версию api и надо префикс там не api, а apiV2 что то такое и потом ходить везде менять это полный отстой руками. Лучше сразу в переменную вынести

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/chat/chatService.js
> +      }
то же самое что я говорил для auth
Данные преобразование и формирование лучше делать в отдельном сервисе. А Апишки чтоб занимались ток уже непосредственной передачей данных и все.

ну и все комменты что к auth сюда так же ликвидны

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/localSrorage.js
> +}
вот эти штуки в целом как раз можно инкапсулировать внутри authService
так как эта логика вряд ли кому то нужна, кроме самого authServie и небольшой группки компонентов, которые по логике связаны с авторизацией. 

Но в целом можно и так оставить наверное

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/message/messageService.js
> +    const { data } = await apiService.get(`/api/messages/?chat=${id}`);
get у axios принимает вторым аргументов объект params, чтоб руками не формировать квери парамсы. Он сам это сделает

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/message/messageService.js
все советы из auth релевантны и сюда

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/Auth/Auth.jsx
> +  }
можно вынести за ракмки компонента типа на строку 8. Такие штуки не обязательно должны быть в компоненте прям. Ток место занимают

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/Auth/Auth.jsx
> +import "./Auth.scss"
мы вроде все таки на модулях договорились писать. Но да ладно

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/ChatRow/ChatRow.jsx
> +  const time = (chat.last_message && chat.last_message.created_at) ? transformDate(chat.last_message.created_at) : null
два раза проверяешь есть ли у тебя lastMassage объект. Вынеси в переменную. Твои проверки станут короче и скорее всего тебе поможет ещё этот оператор чтоб сократить код
text = lastMessage?.text ?? ''

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/ChatsList/ChatList.jsx
> +    );
else тут не нужен. У тебя же везде в if return стоит

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/DropdownChatListMenu/DropdownChatListMenu.jsx
> +    removeTokens()
кажется, что данная логика должна быть в authServie. Чтоб вся логика по управлению авторизацией и тп была сконцентрирована в одном месте без размазывания по проекту

Я про ремув токен

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageChat/HeaderPageChat.jsx
> +}
не хорошо в одном компоненте писать несколько функций. Лучше разносить. Один файл - один компонент

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/Headers/HeaderPageChat/HeaderPageChat.jsx
> +  const avatarImage = (avatar === null) ? defaultAvatar : avatar
avatar ?? defaultAvatar
https://learn.javascript.ru/nullish-operators

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageMyProfile/PageMyProfile.jsx
>  };
else не надо

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageMyProfile/PageMyProfile.jsx
> +  if (profile !== undefined) {
такие вещи лучше решать через явное состояние 
сделать в состояние типа loadingState
чтоб его возможные значения были аля init | loading | error | success | idle
тогда ты явно будешь понимать, в каком состояние находишься
profile !== undefined  - это косвенный признак. По которому нельзя точно сказать, а почему собственно undefined

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageAuth/PageAuth.scss
удаляем все пустные и ненужные файлы

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/Register/Register.jsx
> +  }
можно вынести за пределы компонента

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/PrivateRoute/PrivateRoute.jsx
> +    return <Outlet />
классное решение
я не знал про такие возможности уже)

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/MessagesList/MessagesList.jsx
> +  const userId = localStorage.getItem("userId");
в userService лучше вынести это

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/components/MessagesList/MessagesList.jsx
> +  }
без else работать будет

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageChat/PageChat.jsx
> +  const getAllChats = async () => {
название столку сбивает
вроде запрос одного чата
а называет getAllChats.

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageChat/PageChat.jsx
> +    getMessages()
задержку между запросами
чаще чем раз в 10-20 секунд опрашивать я думаю нет смысла
если кто то быстро ответил, то задержка не значительная. А если человек пишет большее сообщение. То в целом нет смысла обновлять часто

а у  тебя сейчас дудос сервера идет. И был бы сервер чуть по строже настроен. Он бы тупа забанил тебя за такое количество запросов)

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/page/PageChatList/PageChatList.jsx
>      }
if бла бла логика return
и тогда else тебе не нужен будет
меньше скобок. Легче читать

2024-11-09 09:44 UTC, RomanBarannickov commented on react-chat/src/api/api.config.js
> +    if (originalConfig.url !== "/api/auth/refresh/" && originalConfig.url !== "/api/register/" && error.response) {
как будто бы проверка на url избыточна.
Если даже протух токен для этих api. Бек мимо себя это пропустит потому что у него внутри нет проверки на авторизацию. А все остальные апишки, сами по себе ошибку выкинут

2024-11-11 20:50 UTC, gudzan commented
я пока еще в процессе исправления, а пока что: 
- поправила немного верстку
- убрала дудос
- сделала long polling на список чатов

2024-11-16 07:47 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin 
апрув

2024-11-16 07:47 UTC, RomanBarannickov commented on react-chat/src/page/PageChat/PageChat.jsx
> +    getChat()
единственно вижу немного странно поведение. Что чаты так же запрашиваются. Хотя кажется, что это немного лишнее постоянно перезапрашивать чаты ещё 
![image](https://github.com/user-attachments/assets/cf9f3429-0af0-43e4-ba2f-bea9b13bf25d)


в целом ок. Но лучше не запрашивать лишнее по возможности

2024-11-19 14:33 UTC, merged

2024-11-19 14:34 UTC, martinkomitsky commented
12!